models_config: configs/audio2motion/model/models.yaml
crop_cfg: configs/audio2motion/model/crop_config.yaml
face_parser_weight_path: pretrain_weights/face/face-parsing/79999_iter.pth
resnet_weight_path: pretrain_weights/face/face-parsing/resnet18-5c106cde.pth
need_normalized: true
batch_size: 100
source_max_dim: 1920
source_division: 2
input_height: 256
input_width: 256
output_height: 512
output_width: 512
output_fps: 25
flag_do_torch_compile: false
flag_use_half_precision: false
flag_relative_motion: false
flag_normalize_lip: false
flag_source_video_eye_retargeting: false
flag_eye_retargeting: false
flag_lip_retargeting: false
flag_stitching: true
lip_normalize_threshold: 0.03
source_video_eye_retargeting_threshold: 0.18
anchor_frame: 0
driving_option: expression-friendly
driving_multiplier: 1.0
lib_multiplier: 1.0
driving_smooth_observation_variance: 3.0e-07
animation_region: all
mask_crop: src/utils/resources/mask_template.png
lip_array: src/utils/resources/lip_array.pkl
