appearance_feature_extractor:
  path: pretrain_weights/decode/v1/first_stage/base_models/appearance_feature_extractor.pth
motion_extractor:
  path: pretrain_weights/decode/v1/first_stage/base_models/motion_extractor.pth
spade_generator:
  path: pretrain_weights/decode/v1/first_stage/base_models/spade_generator.pth
warping_module:
  path: pretrain_weights/decode/v1/first_stage/base_models/warping_module.pth
stitching_retargeting_module:
  path: pretrain_weights/decode/v1/first_stage/retargeting_models/stitching_retargeting_module.pth
face_analysis:
  path: pretrain_weights/face/face-parsing/
